import 'package:flutter/material.dart';
import 'package:quiz_app/screen.dart';

import 'constants.dart';
import 'drawer.dart';

class AboutSection extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'About',
      theme: ThemeData.dark(),
      debugShowCheckedModeBanner: false,
      home: MyAboutSection(),
    );
  }
}

class MyAboutSection extends StatefulWidget {
  @override
  _MyAboutSectionState createState() => _MyAboutSectionState();
}

class _MyAboutSectionState extends State<MyAboutSection> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          IconButton(
            icon: Icon(
              Icons.arrow_back,
              color: Colors.white,
              size: 30,
            ),
            onPressed: () {
              setState(() {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) {
                      return MyCustomWidget();
                    },
                  ),
                );
              });
            },
          )
        ],
        title: Text('About'),
        centerTitle: true,
        backgroundColor: Color(0xff37474f),
      ),
      drawer: MyDrawer(),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Container(
              margin: EdgeInsets.all(15.0),
              decoration: BoxDecoration(
                  color: Color(0xff373737),
                  borderRadius: BorderRadius.circular(30.0),
                  boxShadow: [
                    BoxShadow(
                      color: Color(0xff000000).withOpacity(0.7),
                      blurRadius: 25,
                      offset: Offset(5, 10),
                    ),
                  ]),
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  children: [
                    Text(
                      'Welcome D-ENCODER here,\n',
                      style: myMediumTextStyle(),
                    ),
                    Text(
                      'If you are a beginner the i insist you not to rely fully on this app, this app is good no doubt but I suggest you to make your handwritten notes by your self. Learn from this app and by that time make your notes this will help you, make your cheatsheet(a sheet of codes that are used in JavaScript) so when you forget any topic you can go through that notes prepared by you\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'What is JavaScript?\n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'JavaScript is a dynamic computer programming language. It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities.\n\nJavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'What is JavaScript and what does it do?\n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'Before you start learning something new, it’s important to understand exactly what it is and what it does. This is especially useful when it comes to mastering a new programming language.\n\nIn simple terms, JavaScript is a programming language used to make websites interactive. If you think about the basic makeup of a website, you have HTML, which describes and defines the basic content and structure of the website, then you have CSS, which tells the browser how this HTML content should be displayed—determining things like color and font. With just HTML and CSS, you have a website that looks good but doesn’t actually do much. JavaScript brings the website to life by adding functionality. JavaScript is responsible for elements that the user can interact with, such as drop-down menus, modal windows, and contact forms. It is also used to create things like animations, video players, and interactive maps.\n\nNowadays, JavaScript is an all-purpose programming language—meaning it runs across the entire software stack. The most popular application of JavaScript is on the client side (aka frontend), but since Node.js came on the scene, many people run JavaScript on the server side (aka backend) as well. When used on the client side, JavaScript code is read, interpreted, and executed in the user’s web browser. When used on the server side, it is run on a remote computer.\n\nJavaScript isn’t only used to create websites. It can also be used to build browser-based games and, with the help of certain frameworks, mobile apps for different operating systems. The creation of new libraries and frameworks is also making it possible to build backend programs with JavaScript, such as web apps and server apps.\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'Is it still worth learning JavaScript?\n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'The world of web development is constantly moving. With so many new tools popping up all the time, it can be extremely difficult to know where you should focus your efforts. As an aspiring developer, you’ll want to make sure that what you’re learning is still relevant in today’s industry.\n\nIf you’re having doubts about JavaScript, it’s important to know that, since its creation in 1995, JavaScript is pretty much everywhere on the web—and that’s not likely to change any time soon. According to the 2020 StackOverflow developer survey, JavaScript is the most commonly used programming language for the eighth year in a row. It is currently used by 94.5% of all websites and, despite originally being designed as a client-side language, JavaScript has now made its way to the server-side of websites (thanks to Node.js), mobile devices (thanks to React Native and Ionic) and desktop (courtesy of Electron).\n\nAs long as people are interacting with the web, you can assume that JavaScript is highly relevant—there’s no doubt that this is a language worth knowing! With that in mind, let’s look at some of the key benefits of becoming a JavaScript expert.\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'Why learn JavaScript?\n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'The most obvious reason for learning JavaScript is if you have hopes of becoming a web developer. Even if you haven’t got your heart set on a tech career, being proficient in JavaScript will enable you to build websites from scratch—a pretty useful skill to have in today’s job market!\n\nIf you do want to become a web developer, here are some of the main reasons why you should learn JavaScript:\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'JavaScript experts are versatile\n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'JavaScript is an extremely versatile language. Once you’ve mastered it, the possibilities are endless: you can code on the client-side (frontend) using Angular and on the server-side (backend) using Node.js. You can also develop web, mobile, and desktop apps using React, React Native, and Electron, and you can even get involved in machine learning.\n\nIf you want to become a frontend developer, JavaScript is a prerequisite. However, that’s not the only career path open to you as a JavaScript expert. Mastering this key programming language could see you go on to work in full-stack development, games development, information security software engineering, machine learning, and artificial intelligence—to name just a few!\n\nUltimately, if you want any kind of development or engineering career, proficiency in JavaScript is a must.\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'JavaScript experts are in-demand (and well-paid)\n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'JavaScript is the most popular programming language in the world, so it’s no wonder that JavaScript is one of the most sought-after skills in the web development industry today.\n\nAccording to the Devskiller IT Skills and Hiring Report 2020, 72% of companies are looking to hire JavaScript experts. Enter the search term “JavaScript” on job site Indeed and you’ll find over 40,000 jobs requiring this skill (in the US). Run the same search on LinkedIn and the results are in excess of 125,000. \n\nAt the same time, the global demand for JavaScript seems to outweigh the expertise available on the market. According to this 2018 HackerRank report, 48% of employers worldwide need developers with JavaScript skills, while only 42% of student developers claim to be proficient in JavaScript. And, in their most recent report for 2020, HackerRank once again reports that JavaScript is the most popular language that hiring mangers look for in a web developer candidate.\n\nNot only are JavaScript experts in demand—they are also well-paid. In the United States, JavaScript developers earn an average yearly salary of \$111,953 per year. We’ve covered this topic in more detail in our JavaScript salary guide, but as you can see, learning JavaScript can really boost your earning potential as a developer.\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'JavaScript is beginner-friendly\n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'Compared to many other programming languages, JavaScript offers one of the more beginner-friendly entry points into the world of coding. The great thing about JavaScript is that it comes installed on every modern web browser—there’s no need to set up any kind of development environment, which means you can start coding with JavaScript right away!\n\nAnother advantage of learning JavaScript as your first programming language is that you get instant feedback; with a minimal amount of JavaScript code, you’ll immediately see visible results. There’s also a huge JavaScript community on sites like Stack Overflow, so you’ll find plenty of support as you learn.\n\nNot only is JavaScript beginner-friendly; it will also set you up with some extremely valuable transferable skills. JavaScript supports object-oriented, functional, and imperative styles of programming—skills which can be transferred to any new language you might learn later on, such as Python, Java, or C++. JavaScript provides a crucial introduction to key principles and practices that you’ll take with you throughout your career as a developer.\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'Should you learn plain JavaScript first or can you skip to frameworks and libraries? \n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'When deciding whether or not to learn JavaScript, what you’re really asking is whether or not you should learn “vanilla” JavaScript. Vanilla JavaScript just means plain JavaScript without any libraries or frameworks. Let’s explore what this means in more detail now.\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'What is meant by vanilla JavaScript, libraries, and frameworks?\n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'If you research the term “vanilla JavaScript”, you might run into some confusion; however, all you need to know is that vanilla JavaScript is used to refer to native, standards-based, non-extended JavaScript. There is no difference between vanilla JavaScript and JavaScript—it’s just there to emphasize the usage of plain JavaScript without the use of libraries and frameworks.\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'So what are libraries and frameworks?\n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'JavaScript libraries and frameworks both contain sets of prewritten, ready-to-use JavaScript code—but they’re not the same thing. You can think of a framework as your blueprint for building a website: it gives you a structure to work from, and contains ready-made components and tools that help you to build certain elements much quicker than if you were to code them from scratch. Some popular JavaScript frameworks include Angular, React, Vue, and Node.js.\n\nFrameworks also contain libraries. Libraries are smaller than frameworks, and tend to be used for more specific cases. A JavaScript library contains sets of JavaScript code which can be called upon to implement certain functions and features. Let’s imagine you want to code a particular element into your website. You could write, say, ten lines of JavaScript from scratch—or you could take the condensed, ready-made version from your chosen JavaScript library. Some examples of JavaScript libraries include jQuery, Lodash, and Underscore.\n\nThe easiest way to understand how frameworks and libraries work together is to imagine you are building a house. The framework provides the foundation and the structure, while the library enables you to add in ready-made components (like furniture) rather than building your own from scratch.\n\nYou can learn more about the relationship between languages and libraries in this post explaining the main differences between JavaScript and jQuery. For now, let’s go back to our original question: How important is it to learn vanilla JavaScript?\n',
                      style: mySmallTextStyle(),
                    ),
                    Text(
                      'Should you learn vanilla JavaScript first?\n',
                      style: myBigTextStyle(),
                    ),
                    Text(
                      'When it comes to learning JavaScript, it can be tempting to skip ahead to those time-saving frameworks and libraries we just talked about—and many developers do. However, there are many compelling arguments for learning plain JavaScript first.\n\nWhile JavaScript frameworks may help you get the job done quicker, there’s only so far you can go if you don’t understand the core concepts behind these frameworks. Frontend developer Abhishek Nagekar describes how not learning vanilla JavaScript came back to bite him when he started learning the JavaScript frameworks Node and Express:\n',
                      style: mySmallTextStyle(),
                    ),
                    Row(
                      children: [
                        Expanded(
                          flex: 1,
                          child: Container(
                            height: 300,
                            child: Text(''),
                            decoration: new BoxDecoration(
                              borderRadius: new BorderRadius.circular(4.0),
                              color: Color(0xff9C9C9C),
                            ),
                          ),
                        ),
                        SizedBox(
                          width: 20,
                        ),
                        Expanded(
                          flex: 20,
                          child: Text(
                            '“As I went to write more and more code in Node and Express, I began to get stuck at even the tiniest problems. Suddenly, I was surrounded with words like callbacks, closures, event loop and prototype. It felt like I got a reintroduction to JavaScript, but this time, it was not a toddler playing in its cradle, it was something of a mysterious monster, challenging me on every other step for not having taken it seriously.”\n',
                            style: mySmallTextStyle(),
                          ),
                        ),
                      ],
                    ),
                    Text(
                      '\nThe above Tweet references a long-running joke within the developer community, and although it dates way back to 2015, it’s still highly relevant today. If you want to become a developer who can innovate, not just execute, you need to understand the underlying principles of the web—not just the shortcuts. This means learning vanilla JavaScript before you move on to frameworks. In fact, understanding plain JavaScript will help you later on when it comes to deciding whether to use a framework for a certain project, and if so, which framework to use.\n\nUltimately, if you want to work as a web developer, it’s inevitable that you’ll encounter JavaScript at almost every turn. Learning plain JavaScript first will make you a versatile engineer who can work on both the frontend and the backend, and it’ll equip you to solve complex problems independently—a key skill in the industry.\n',
                      style: mySmallTextStyle(),
                    ),
                    SizedBox(
                      height: 20,
                    ),
                    CircleAvatar(
                      backgroundImage: AssetImage('assets/images/het.jpg'),
                      radius: 60,
                    ),
                    SizedBox(
                      height: 20,
                    ),
                    Text(
                      'D-ENCODER',
                      style: TextStyle(
                        fontFamily: 'CM Sans Serif',
                        fontSize: 30,
                        color: Colors.white,
                      ),
                    ),
                    SizedBox(
                      height: 5,
                    ),
                    Text(
                      'FLUTTER DEVELOPER',
                      style: TextStyle(
                        fontFamily: 'Source Sans Pro',
                        color: Colors.blue,
                        fontSize: 20.0,
                        letterSpacing: 2.5,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    SizedBox(
                      height: 5,
                    ),
                    Card(
                      margin:
                          EdgeInsets.symmetric(vertical: 10.0, horizontal: 2.0),
                      child: ListTile(
                        leading: Icon(
                          Icons.email,
                          color: Colors.white,
                        ),
                        title: Text(
                          'hetcjoshi1684@gmail.com',
                          style: TextStyle(
                            color: Colors.white,
                            fontFamily: 'Source Sans Pro',
                            fontSize: 18,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 5,
                    ),
                    Text(
                      'I have created the app the UI Designs and the Layouts have been created by me and if you found any bug the please report us.',
                      style: TextStyle(
                        color: Colors.white.withOpacity(1),
                        fontSize: 16,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                    SizedBox(
                      height: 20,
                    ),
                    CircleAvatar(
                      backgroundImage: AssetImage('assets/images/kunal.jpg'),
                      radius: 60,
                    ),
                    SizedBox(
                      height: 20,
                    ),
                    Text(
                      'TYPECASTED_1',
                      style: TextStyle(
                        fontFamily: 'CM Sans Serif',
                        fontSize: 30,
                        color: Colors.white,
                      ),
                    ),
                    SizedBox(
                      height: 5,
                    ),
                    Text(
                      'FLUTTER DEVELOPER',
                      style: TextStyle(
                        fontFamily: 'Source Sans Pro',
                        color: Colors.blue,
                        fontSize: 20.0,
                        letterSpacing: 2.5,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    SizedBox(
                      height: 5,
                    ),
                    Text(
                      'I have contributed by deciding the colour combinations of this app.',
                      style: TextStyle(
                        color: Colors.white.withOpacity(1),
                        fontSize: 16,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
